### PR TITLE
Fix lean_profile_proof cleanup crash on Windows

### LINKED ISSUE #216: lean_profile_proof is unusable on Windows: os.killpg in the cleanup finally
## Summary

`lean_profile_proof` is unusable on Windows: every call fails with `module 'os' has no attribute 'killpg'`, raised from the cleanup path rather than from the profiling work itself.

## Environment

Windows 11, Python 3.12.1, `lean-lsp-mcp` 0.29.0 (current release), Lean 4.32.2, Mathlib `v4.32.2`.

## Reproduction

```json
{
  "name": "lean_profile_proof",
  "arguments": { "file_path": "<project>/Playground/Gauss.lean", "line": 9, "top_n": 3 }
}
```

```
Error executing tool lean_profile_proof: module 'os' has no attribute 'killpg'
```

## Cause

`src/lean_lsp_mcp/profile_utils.py` (unchanged on current `main`):

```python
def _kill_process_group(pid: int) -> None:
    """Kill an entire process group. No-op if already dead."""
    try:
        os.killpg(os.getpgid(pid), 9)
    except (ProcessLookupError, OSError):
        pass
```

called from `_run_lean_profile`:

```python
try:
    stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    return stdout.decode("utf-8", errors="replace")
except asyncio.TimeoutError:
    raise TimeoutError(f"Profiling timed out after {timeout}s")
finally:
    _kill_process_group(proc.pid)
```

Three things combine, each checked on this machine:

1. `os.killpg` and `os.getpgid` do not exist on Windows — `hasattr(os, "killpg")` and `hasattr(os, "getpgid")` are both `False`.
2. `AttributeError` is a subclass of neither `ProcessLookupError` nor `OSError`, so `except (ProcessLookupError, OSError)` does not catch it.
3. The call sits in a `finally`, so it runs on every path. Whatever `_run_lean_profile` was about to produce — the decoded profile output, or the `TimeoutError` from the `except` branch — is replaced by the `AttributeError`, so the caller can never observe the real outcome.

`start_new_session=True` is also POSIX-only. On Windows it is accepted and silently ignored (verified: `subprocess.Popen(..., start_new_session=True)` raises nothing and the child runs normally), so there is no shared process group to kill there in the first place.

## `lean --profile` itself is fine on Windows

`profile_theorem` extracts the header plus the target theorem into a temp file and profiles that. Running the same command by hand in the same project, directly on the source file instead of the extract:

```
lake env lean --profile -Dtrace.profiler=true -Dtrace.profiler.threshold=0 Playground/Gauss.lean
```

exits `0` and emits ~20 MB / ~58k lines of trace output, with the usual per-step `[Elab.*]` entries. So the Windows problem is confined to the Python wrapper.

## Origin

Introduced by 47f035e6 (*"rm orphaned profile processes on timeout"*, 2026-03-10), which added `_kill_process_group`, the `os.killpg` call, `start_new_session=True` and the `finally` hook.

It landed 8 days after 103f2e15 (*"[fix] Windows: encoding, path normalization, loogle cache dir"*), which may be why the file was not re-checked for Windows compatibility afterwards.

## Prior art in this repo

`src/lean_lsp_mcp/repl.py` already handles exactly this case:

```python
if platform.system() != "Windows":
    os.killpg(os.getpgid(proc.pid), 9)
else:
    proc.kill()
```

## Suggested fix

Mirroring `repl.py` in `_run_lean_profile`'s `finally` also covers the Windows side of the orphan-process problem the original commit set out to solve:

```python
finally:
    if platform.system() != "Windows":
        _kill_process_group(proc.pid)
    else:
        proc.kill()
```

Adding `AttributeError` to the caught exception tuple would stop the crash, but would leave orphaned `lean` processes on Windows — the `_run_lean_profile` docstring notes these are ~2.5 GB — so the platform branch looks preferable.

This is the only Windows-specific failure I hit while exercising the server's tools on this setup.

### PR DESCRIPTION
**Pull request by MohammedAlkindi**
Fixes #216.

## Summary

Every `lean_profile_proof` call on Windows fails with `module 'os' has no attribute 'killpg'`, raised from `_run_lean_profile`'s `finally` after the profile output has already been produced. `_kill_process_group` calls `os.killpg(os.getpgid(pid), 9)`, neither function exists on Windows, and `AttributeError` isn't caught by the `except (ProcessLookupError, OSError)` guard.

The fix branches the cleanup exactly the way `Repl.close` already does elsewhere in this codebase: POSIX kills the process group (unchanged), Windows kills the process itself. `_kill_process_group` now takes the `Process` object so the Windows branch can use `proc.kill()`.

## Testing

Both platforms are simulated in the new tests (monkeypatched `platform.system` and `os.killpg`/`os.getpgid`, fake subprocess), so each case runs wherever the suite runs:

- On current `main`'s `profile_utils.py`, the Windows-case test fails with the exact reported error — `AttributeError: module 'os' has no attribute 'killpg'` out of `profile_utils.py`'s cleanup — and the POSIX-case test passes (that behavior is unchanged).
- With this fix: `tests/unit/test_profile_utils.py` → 15 passed (13 existing + these 2).
- Full `tests/unit` on this machine (native Windows 11, Python 3.13): 8 failures in other modules (`test_cli`, `test_client_utils`, `test_file_utils`, `test_loogle`, `test_server` path/env-sanitization cases) are identical with and without this change — pre-existing local-environment failures, not introduced here. The only delta is the new Windows-case test flipping fail → pass.

Limit worth stating: I haven't run the end-to-end `lean_profile_proof` tool call on this machine (no Lake project wired up here); the reporter's traceback places the crash in this cleanup path, which the tests exercise through `_run_lean_profile`'s real `finally`.

### CODE REVIEW

**Comment by TATANKA97** [comment]
The description notes the end to end tool call was not run. I have that setup, so here are the results.

Applied this diff to an installed 0.29.0 and called `lean_profile_proof` through the MCP server. Windows 11, Python 3.12.1, Lean 4.32.2, Mathlib `v4.32.2`, real Lake project.

No crash, valid output in 22.8s:

```json
{
  "ms": 372.5,
  "categories": {
    "ring": 168.0,
    "overlappingInstancesLinter": 95.4,
    "tacticAnalysis": 91.8,
    "elaboration": 55.0,
    "type checking": 23.2,
    "norm_num": 21.7,
    "typeclass inference": 19.8
  }
}
```

Process snapshot taken before and after the call: no leftover `lake.exe` or `lean.exe`.

I also checked the orphan question separately, since Windows has no POSIX process groups and killing the spawned process could in principle leave the tree behind. With a live tree (`lake.exe` as the spawned process, `lean.exe` as its child) I terminated only the spawned process, which is what `proc.kill()` does here, and both died. So the Windows branch does not reintroduce what 47f035e6 was guarding against.

One observation I did not investigate: `lines` came back empty while `categories` was populated, for the theorem used in the issue.

Patch reverted afterwards, so this was published 0.29.0 plus this diff only.

**Comment by MohammedAlkindi** [comment]
Thank you — that is the exact gap the PR body flagged, and the orphan check covers the one thing I could not test from the issue alone.

On the empty `lines`: that is independent of this patch, and it is not a regression. `lines` and `ms` are produced by different things in `profile_theorem`:

- `proof_items` is built at `profile_utils.py:220` from the source file, **before** the subprocess starts at line 229.
- `ms` is `total`, which `_extract_line_times` assigns from the `Elab.definition.value` trace (line 125), or `Elab.async` (line 127). It never depends on a line match.
- `lines` is `top_lines`, which needs `_match_line` to bind a tactic trace to a source line, and then survive the `ms >= total * 0.01` filter.

So `ms: 372.5` with `lines: []` means the traces parsed and nothing bound to a source line. This patch only changes `_kill_process_group`, which runs in the `finally` of `_run_lean_profile` after `output` is already captured, so it cannot reach either field.

I did check whether bullet matching was silently broken, since a bullet-structured proof is the obvious suspect. It is not — `not tactic` at line 135 is deliberate: a bullet step's trace carries the marker and nothing else, so `"·"` strips to `""` and `not ""` is `True`, which is the `is_bullet` the source side computes. Your suite already pins it, and it passes at `2be04fc`:

```
$ pytest tests/unit/test_profile_utils.py -k "TestExtractLineTimes or TestBuildProofItems" -q
......                                                                   [100%]
6 passed, 9 deselected, 1 warning in 0.47s
```

That leaves the 25-character prefix comparison in `_match_line` plus the `used` set as the remaining candidate, and I would rather not guess at it: I do not have a Lean toolchain on this machine, so I cannot reproduce your theorem and I have not diagnosed it. If you can share the theorem, the binding is cheap to trace offline. Either way it is pre-existing and orthogonal to this fix, so I have deliberately left it alone rather than widening a cleanup-crash patch into the matching logic.

**Comment by TATANKA97** [comment]
Rather than the theorem, here is the cause. Filed separately as #220 since it is pre-existing and orthogonal to this PR, exactly as you said.

It is not the 25 character comparison. That receives input which is already dirty: the profiler prefixes every trace message with a status marker, so `_extract_line_times` sees `✅️ rw [h]` and `.lstrip("·*- \t")` does not remove it. Codepoints from a real run: `0x2705`, `0xfe0f`, `0x20`.

Controlled on this repo's own `tests/test_project/ProfileTest.lean`, profiling `simple_by`, same traces both times with only the strip differing:

```
strip as it is today   -> line_times={}            total=19.2
strip + status marker  -> line_times={5: 13.401}   total=19.2
```

Your reading of the bullet branch holds as written, but it cannot be reached in production for the same reason: the marker keeps `tactic` non empty, so `not tactic` is always `False`. The unit tests exercise that path because they build messages without the marker, which is also why the suite stays green while nothing binds.

So your diff is clear on this. Nothing in it touches either field, and the empty `lines` predates it.

**Comment by MohammedAlkindi** [comment]
That is the cause, and it corrects my stated candidate — I said the 25-character comparison was the remaining suspect and it is not: the input reaching it is already unmatchable. Confirmed your mechanism locally:

```python
>>> '✅️ rw [h]'.split('\n')[0].strip().lstrip('·*- \t')
'✅️ rw [h]'   # marker survives; neither startswith direction can fire
```

#220 is the right place for it and the right scope split. Thanks for closing the loop on both halves — the end-to-end run and now the actual binding failure.
